/**
 * End-to-end tests: pdf-parse-new + XTB parsers.
 *
 * Unlike rates.test.js / parsers-xtb.test.js (which feed pre-extracted text
 * fixtures into the parsers), this suite exercises the FULL pipeline that
 * runs in production:
 *   1. pdf-parse-new reads the binary PDF
 *   2. The extracted text is handed to parseXtbDividends / parseXtbPortfolio
 *
 * The fixtures under test/fixtures/*.pdf are deterministic, anonymized
 * synthetic PDFs generated by scripts/generate-test-pdfs.js. They contain
 * NO personal data and pin PDF metadata to fixed values.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const pdfParse = require('pdf-parse-new');
const { parseXtbDividends, parseXtbPortfolio } = require('../lib/parsers/xtb');

const FIXTURES = path.join(__dirname, 'fixtures');

async function extractText(pdfFile) {
  const buf = fs.readFileSync(path.join(FIXTURES, pdfFile));
  const { text } = await pdfParse(buf);
  return text;
}

test('e2e: pdf-parse + parseXtbDividends on anonymized PDF', async () => {
  const text = await extractText('xtb-dividends-anonymized.pdf');
  const result = parseXtbDividends(text, 2025);

  assert.equal(result.dividendRows.length, 2, 'should capture both dividend rows');
  assert.equal(result.dividends.grossRON, 1000 + 500.50);
  assert.equal(result.dividends.taxWithheldRON, 100 + 50.05);

  assert.equal(result.interestRows.length, 1, 'should capture the interest row');
  assert.equal(result.interest.grossRON, 200);
  assert.equal(result.interest.taxWithheldRON, 20);
});

test('e2e: pdf-parse + parseXtbPortfolio on anonymized PDF', async () => {
  const text = await extractText('xtb-portfolio-anonymized.pdf');
  const result = parseXtbPortfolio(text, 2025);

  assert.equal(result.countries.length, 3, 'should capture all three country rows');

  const names = result.countries.map(c => c.country);
  assert.deepEqual(names, ['Irlanda', 'Statele Unite', 'Germania']);

  // Irlanda: RON, short loss 5000
  assert.equal(result.countries[0].currency, 'RON');
  assert.equal(result.countries[0].shortLoss, 5000);

  // Germania: EUR row, converted via 2025 EUR/RON (5.0415)
  assert.equal(result.countries[2].currency, 'EUR');
  assert.equal(result.countries[2].longGain, 50);
  assert.equal(result.countries[2].longGainRON, 50 * 5.0415);
});

test('e2e: anonymized PDFs contain NO original personal data', async (t) => {
  // Defensive check that complements scripts/generate-test-pdfs.js: even after
  // any future regeneration, this test fails if real data leaks into the bytes.
  //
  // The list of banned tokens is loaded from a LOCAL-ONLY file
  // `test/fixtures/banned-tokens.local.json` which is .gitignored. The shape
  // matches `test/fixtures/banned-tokens.example.json` (committed, with
  // placeholders). To enable the regression check on your machine, copy the
  // example file to `banned-tokens.local.json` and fill in the actual values
  // you want to keep out of the public fixtures. We never commit PII.
  let banned;
  try {
    banned = require('./fixtures/banned-tokens.local.json');
  } catch (_) {
    banned = null;
  }
  if (!Array.isArray(banned) || banned.length === 0) {
    t.skip('No test/fixtures/banned-tokens.local.json — anonymization regression test skipped. Copy the .example.json to .local.json to enable.');
    return;
  }

  for (const pdf of ['xtb-dividends-anonymized.pdf', 'xtb-portfolio-anonymized.pdf']) {
    const raw = fs.readFileSync(path.join(FIXTURES, pdf)).toString('binary');
    for (const banned_token of banned) {
      assert.equal(
        raw.includes(banned_token), false,
        `Fixture ${pdf} unexpectedly contains "${banned_token}" — anonymization broken`
      );
    }
  }
});

test('e2e: anonymized PDFs have safe metadata', async () => {
  // PDF /Info dictionary must be pinned to safe values, not leak the
  // generation machine's identity or local time.
  for (const pdf of ['xtb-dividends-anonymized.pdf', 'xtb-portfolio-anonymized.pdf']) {
    const buf = fs.readFileSync(path.join(FIXTURES, pdf));
    const { info } = await pdfParse(buf);

    assert.equal(info.Author, 'D212TaxHelper Test Suite');
    assert.equal(info.Producer, 'D212TaxHelper');
    assert.equal(info.Creator, 'D212TaxHelper');
    assert.equal(info.Title, 'D212TaxHelper Test Fixture');
    // Fixed deterministic date — not the time the PDF was generated.
    assert.equal(info.CreationDate, 'D:20250115100000Z');
    assert.equal(info.ModDate, 'D:20250115100000Z');
  }
});
